/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AdminManager: typeof import('./../components/index/AdminManager.vue')['default']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    EchartsContainer: typeof import('./../components/EchartsContainer.vue')['default']
    FlowStat: typeof import('./../components/index/FlowStat.vue')['default']
    Map: typeof import('./../components/index/Map.vue')['default']
    OrderTrendStatistics: typeof import('./../components/index/OrderTrendStatistics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodayCurrentData: typeof import('./../components/index/TodayCurrentData.vue')['default']
    TopPurchase: typeof import('./../components/index/TopPurchase.vue')['default']
    TopWebsite: typeof import('./../components/index/TopWebsite.vue')['default']
    TypeDistribution: typeof import('./../components/index/TypeDistribution.vue')['default']
    UserTrendStatistics: typeof import('./../components/index/UserTrendStatistics.vue')['default']
  }
}
